# Generated by Django 4.0.6 on 2022-08-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_category_chart_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['user', 'name']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['user', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
