# Generated by Django 4.0.6 on 2022-08-12 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0005_expense_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['user', '-created']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['user', '-created']},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='color',
        ),
        migrations.AlterField(
            model_name='expense',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
