# Generated by Django 4.1 on 2022-08-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_category_color_alter_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.FloatField(),
        ),
    ]
