# Generated by Django 4.1 on 2022-08-15 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_expense_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, 'the field must contain at least 1 characters')]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, 'the field must contain at least 1 characters')]),
        ),
    ]
