# Generated by Django 4.1 on 2022-08-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='number',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
