# Generated by Django 4.1 on 2022-08-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_alter_limit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
